# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Embassy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=200)),
                ('street_address', models.CharField(db_column='Address', max_length=200)),
                ('city', models.CharField(db_column='City', max_length=50)),
                ('phone_number', models.IntegerField(db_column='Phone Number', default=-1)),
                ('fax_number', models.IntegerField(blank=True, db_column='Fax Number', null=True)),
                ('email_address', models.CharField(db_column='Email', max_length=200)),
                ('website', models.CharField(db_column='Link', max_length=200)),
                ('government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='government', to='finder.Country')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='finder.Country')),
            ],
        ),
    ]
