# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import finder.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='embassy',
            options={'verbose_name': 'Embassy', 'verbose_name_plural': 'Embassies'},
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, validators=[finder.models.validate_nonempty, finder.models.validate_string_length_three, finder.models.validate_string_all_caps]),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_column='Name', max_length=50, validators=[finder.models.validate_nonempty]),
        ),
        migrations.AlterField(
            model_name='embassy',
            name='email_address',
            field=models.CharField(blank=True, db_column='Email', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='embassy',
            name='fax_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_column='Fax Number', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='embassy',
            name='name',
            field=models.CharField(db_column='Name', max_length=200, validators=[finder.models.validate_nonempty]),
        ),
        migrations.AlterField(
            model_name='embassy',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_column='Phone Number', default=-1, max_length=128),
        ),
        migrations.AlterField(
            model_name='embassy',
            name='website',
            field=models.CharField(blank=True, db_column='Link', max_length=200, null=True),
        ),
    ]
