# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import finder.models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_auto_20170303_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, validators=[finder.models.validate_nonempty, finder.models.validate_string_length_three, finder.models.validate_string_all_caps]),
        ),
    ]
